# Generated by Django 4.1.1 on 2022-09-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('doj', models.DateField()),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'todo_Employees',
            },
        ),
        migrations.CreateModel(
            name='Superiors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('doj', models.DateField()),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'todo_Superiors',
            },
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100, null=True)),
                ('enddate', models.DateField()),
                ('isWorkDone', models.BooleanField(default=False)),
                ('SupervisorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.superiors')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklists', to='todo.employees')),
            ],
            options={
                'db_table': 'todo_Worklist',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='SupervisorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='todo.superiors'),
        ),
    ]
